export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCES = 'ADD_PRODUCT_SUCCES';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const DOWNLOAD_PRODUCTS = 'DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCES = 'DOWNLOAD_PRODUCTS_SUCCES';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCES = 'DELETE_PRODUCT_SUCCES';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START';
export const EDIT_PRODUCT_SUCCES = 'EDIT_PRODUCT_SUCCES';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
